spring.application.name=economia-historia-api

# Dados de Conexão com o PostgreSQL Adaptáveis para a Equipa
# vocês devem substituir esses campos pelos vossos dados reais família
spring.datasource.url=jdbc:postgresql://localhost:5432/economia_historia_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:a_tua_senha_aqui}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - Criação automática de tabelas com base no teu Diagrama de Classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuração de Segurança Temporária para Testes
spring.security.user.name=admin
spring.security.user.password=admin123