# Nome do Projeto
spring.application.name=economia-historia-api

# Dados de Conexão com o MySQL Local (Adaptável para a equipa)
spring.datasource.url=jdbc:mysql://localhost:3306/economia_historia_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:a_tua_senha_do_mysql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Criação automática de tabelas para o MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuração de Segurança Temporária para Testes
spring.security.user.name=admin
spring.security.user.password=admin123